---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    app: backend1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend1
        image: localhost:5000/backend1
        ports:
        - containerPort: 8081
        - containerPort: 8686

---
kind: Service
apiVersion: v1
metadata:
  name: backend1
spec:
  type: NodePort
  selector:
    app: backend1
  ports:
  - name: app
    protocol: TCP
    targetPort: 8081
    port: 8081
    nodePort: 31100
  - name: jmx
    protocol: TCP
    targetPort: 8686
    port: 8686
    nodePort: 31101
