---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centraldogma
  labels:
    app: centraldogma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centraldogma
  template:
    metadata:
      labels:
        app: centraldogma
    spec:
      containers:
      - name: centraldogma
        image: line/centraldogma:0.32.1
        ports:
        - containerPort: 36462

---
kind: Service
apiVersion: v1
metadata:
  name: centraldogma
spec:
  type: NodePort
  selector:
    app: centraldogma
  ports:
  - protocol: TCP
    targetPort: 36462
    port: 36462
    nodePort: 30002
