---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /internal/metrics
    spec:
      containers:
      - name: frontend
        image: localhost:5000/frontend
        env:
        - name: JAVA_OPTS
          value: >-
            -Djava.rmi.server.hostname=127.0.0.1
            -Dcom.sun.management.jmxremote
            -Dcom.sun.management.jmxremote.rmi.port=8686
            -Dcom.sun.management.jmxremote.port=8686
            -Dcom.sun.management.jmxremote.local.only=false
            -Dcom.sun.management.jmxremote.ssl=false
            -Dcom.sun.management.jmxremote.authenticate=false
            -XX:StartFlightRecording=name=on_startup,filename=/root/flight_recording.jfr,dumponexit=true,delay=2m,maxsize=512m
            -Xms128m -Xmx128m
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: CENTRALDOGMA_SERVER_HOST
          value: centraldogma.default.svc.cluster.local
        - name: CENTRALDOGMA_SERVER_PORT
          value: "36462"
        ports:
        - containerPort: 8080
        - containerPort: 8686

---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: app
    protocol: TCP
    targetPort: 8080
    port: 8080
    nodePort: 31000
