---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  labels:
    app: backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: /internal/metrics
    spec:
      containers:
      - name: backend2
        image: localhost:5000/backend2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: CENTRALDOGMA_SERVER_HOST
          value: centraldogma.default.svc.cluster.local
        - name: CENTRALDOGMA_SERVER_PORT
          value: "36462"
        ports:
        - containerPort: 8082
        - containerPort: 8686

---
kind: Service
apiVersion: v1
metadata:
  name: backend2
spec:
  type: NodePort
  selector:
    app: backend2
  ports:
  - name: app
    protocol: TCP
    targetPort: 8082
    port: 8082
    nodePort: 31200
