zipkin:
  endpoint: http://127.0.0.1:9411/api/v2/spans

api-servers:
  backend1:
  - host: 127.0.0.1
    port: 8081
  - host: 127.0.0.1
    port: 18081
  backend2:
  - host: 127.0.0.1
    port: 8082
  backend3:
  - host: 127.0.0.1
    port: 8083
  backend4:
  - host: 127.0.0.1
    port: 8084
  - host: 127.0.0.1
    port: 18084
  # via `kubectl proxy`
  kubernetes:
    host: 127.0.0.1
    port: 8001
    scheme: http

centraldogma:
  server:
    host: 127.0.0.1
    port: 30002

kubernetes:
  namespace: default

logging:
  level:
    info.matsumana.armeria: DEBUG
