zipkin:
  endpoint: http://127.0.0.1:9411/api/v2/spans

api-servers:
  backend1:
  - host: 127.0.0.1
    port: 8081
  backend2:
  - host: 127.0.0.1
    port: 8082
  backend3:
  - host: 127.0.0.1
    port: 8083
  backend4:
  - host: 127.0.0.1
    port: 8084
